import "./globals.css";
import type { Metadata } from "next";
import { cn } from "@/lib/utils";
import { fontSans } from "@/lib/fonts";
import { ThemeProvider } from "@/components/theme-provider";
import { ReduxProvider } from "@/redux/provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body
          className={cn(
            "min-h-screen bg-background font-sans antialiased",
            fontSans.variable
          )}
        >
          <ReduxProvider>
            <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
              <div className="relative flex min-h-screen flex-col">
                <div className="flex-1">
                  <div className="container relative">
                    <section>
                      <div className="overflow-hidden rounded-[0.5rem] border bg-background shadow mt-10">
                        {children}
                      </div>
                    </section>
                  </div>
                </div>
              </div>
            </ThemeProvider>
          </ReduxProvider>
        </body>
      </html>
    </>
  );
}
