version: '3'

services:
  backend:
    container_name: xepelin-backend
    build:
      context: ../backend
    ports:
      - "4000:4000"
  frontend:
    container_name: xepelin-frontend
    build:
      context: ../frontend
    ports:
      - "3000:3000"
  postgres:
    image: postgres:12-alpine
    container_name: xepelin-postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - xepelin-data:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
volumes:
  xepelin-data:

